### ISSUE TITLE
changing timeframe on the "Data Collected" graph does not work

### ISSUE THREAD

**Issue by WoMeijerPhD** [datacentricdesign/bucket#18]
# Issue
When I select a different time scale on the "Data Collected" graph, nothing changes to the graph, even though I know data was collected in the past 3 months.
![image](https://user-images.githubusercontent.com/79914012/125744655-43a2a1dc-4d76-4ef4-b936-66488867148b.png)

# Stats
Chrome: Version 92.0.4515.93 (Official Build) beta (x86_64)
OS: mac OSX 11.4 (20F71)

**Comment by jackybourgeois** [comment]
Thanks @WoMeijerPhD, this looks like a Chrome specific issue, the drop down menu failing to trigger the graph update. On the todo list!

**Comment by jackybourgeois** [comment]
Fixed by handling changes in <select> with the change property.
