### ISSUE TITLE
Authentication issue when updating value, not when creating.

### ISSUE THREAD

**Issue by WoMeijerPhD** [datacentricdesign/bucket#20]
- [x] Log in and get access token
- [x] use access token to create/find thing
- [x] use access token to create property on the thing
- [ ] **use access token to update property**

That's where it's falling apart. I receive the following response from the server (with error code 500):

```
DCD Hub Error: Access denied - Authentication information missing, malformed or invalid
    at new DCDError (/usr/app/node_modules/@datacentricdesign/types/DCDError.ts:26:9)
    at AuthService.<anonymous> (/usr/app/src/auth/AuthService.ts:115:11)
    at step (/usr/app/src/auth/AuthService.ts:33:23)
    at Object.next (/usr/app/src/auth/AuthService.ts:14:53)
    at fulfilled (/usr/app/src/auth/AuthService.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
``` 

This error is the same when using a version of ioSense that was confirmed to be working, I will poke around at the python SDK and try and reflect changes in the Dart version, but I would love to double check in case the server is misbehaving.

**Comment by jackybourgeois** [comment]
Hi @WoMeijerPhD, I role out a new release on the production server last week. Top of my head it included a fix on the property scope which was not checked properly before. Your app scope must include dcd:properties if your app uses the properties API.

Note that if you change your scope you need to sign out and sign up again to generate a token with this new scope.

**Comment by WoMeijerPhD** [comment]
Beautiful! It works now! Thanks for the quick reply!

Just for anyone who would happen to read this, I have scopes set as:
```
    'openid',
    'offline',
    'email',
    'profile',
    'dcd:public',
    'dcd:things',
    'dcd:properties'
```
