### ISSUE TITLE
Attempting to create a new property for a new "thing" results in an error

### ISSUE THREAD

**Issue by WoMeijerPhD** [datacentricdesign/bucket#7]
When trying to add a new property, a toaster notification pops up:

![image](https://user-images.githubusercontent.com/79914012/110926654-f5c01680-8324-11eb-98ce-6b989426fec7.png)

This happened for two different test "things" and every data type from the drop down menu

**Comment by jackybourgeois** [comment]
Hi @WoMeijerPhD, thanks for trying out!

Intriguing. Just creating a property for a new thing right now without an error message (type 'Accelerometer'). Are you trying on your own instance of Bucket or on tudelft.nl?

Could you give a screenshot of your form (new property), right before submitting it?

**Comment by WoMeijerPhD** [comment]
This is on the tudelft.nl instance of Bucket.

And the following is the form for a new property:

![image](https://user-images.githubusercontent.com/79914012/110929867-bd223c00-8328-11eb-9a83-cdf878dd3e24.png)


Some obscure error with the drop down? (since typeid is not being set?)

**Comment by jackybourgeois** [comment]
I can only see a web browser difference here. I am testing with Firefox, which one are you using?

**Comment by WoMeijerPhD** [comment]
I am using `Google Chrome Version 89.0.4389.82 (Official Build) (x86_64)`

**Comment by WoMeijerPhD** [comment]
I am not an expert in Angular, but there does seem to be some weirdness about the dropdown component and chrome.

One thing I found [here](https://stackoverflow.com/questions/55846922/angular-click-not-working-on-chrome-when-using-select-option) talks about using (change) not (click).

[Looking at the code, it currently uses (click)](https://github.com/datacentricdesign/bucket/blob/efc692257fdd192ba0186d8791bbb5ad04187a6f/bucket-ui/src/app/thing-bucket/thing/thing.component.html#L70)

**Comment by jackybourgeois** [comment]
OK, thanks for the pointer. I pushed a fix that relies on change instead of click. On my side, it works both on Firefox and chrome. Let me know if that fixes your problem.

**Comment by WoMeijerPhD** [comment]
![image](https://user-images.githubusercontent.com/79914012/110949255-adafec80-8342-11eb-8e10-799759a00a44.png)

it works for me!
